Nuevo procedimiento de alta de socies
python-spain/web pull request #11
Opened 2017-08-31 21:38 UTC by yamila-moreno

Equipo redactor @delapuente @Nekmo @italofarve @rebost Aquí el PR que os comenté. Si podéis echar un vistazo, sería genial (¿se entiende bien el proceso? ¿se entiende bien que animamos a socios y socias a acompasarse con la fecha de la Asociación?); pero por favor, no lo mergeéis hasta que @Juanlu001 no de el visto bueno a la redacción y sobre todo al contenido.

@Juanlu001 confirma que esto encaja con lo que hemos hablado en JD, por favor.

¡Gracias a todos!

2017-08-31 21:47 UTC, astrojuanlu requested changes
He añadido un pequeño comentario pero por lo demás me parece que está perfecto. ¡Muchas gracias @yamila-moreno!

2017-08-31 21:47 UTC, Juanlu001 commented on content/pages/hazte-socio.md
> +Antes de renovarla, te invitamos a que domicilies el pago o acoples tu renovación manual a febrero, nos facilitarías mucho la gestión a la Asociación.
s/acoples/acompases/g

Y añadiría una frase que sea «para acompasar tu cuota con el resto de la Asociación, sigue leyendo». Al principio leyendo en diagonal me he saltado esta parte y me he despistado un poco, estaría bien hacer un poco más de énfasis.

2017-08-31 21:50 UTC, yamila-moreno commented
Gracias por el feedback, he añadido tus cambios.

2017-08-31 21:52 UTC, yamila-moreno commented on content/pages/hazte-socio.md
> +Antes de renovarla, te invitamos a que domicilies el pago o acoples tu renovación manual a febrero, nos facilitarías mucho la gestión a la Asociación.
done!

2017-08-31 21:53 UTC, astrojuanlu approved these changes

2017-09-03 17:05 UTC, italofarve commented
Ha quedado muy bien. Muchas gracias @yamila-moreno & @Juanlu001

2017-09-04 07:07 UTC, yamila-moreno commented
Estupendo @italofarve gracias por la revisión. ¿Qué hace falta para mergear esto? Después, si está todo ok, también habría que mergear #12 y #6 (este último especialmente importante que lleva tiempo sin feedback después del currazo).

2017-09-04 09:31 UTC, Juanlu001 commented
@python-spain/equipo-editor En otras palabras: si por vosotros está listo, mergead :) Si no tenéis permiso, avisadnos.

2017-09-05 11:01 UTC, yamila-moreno commented
@italofarve @Nekmo @rebost @delapuente ¿Podéis mergear esto y después #12 y también #6? Mil gracias :D

2017-09-05 11:05 UTC, matias-pizarro approved these changes

2017-09-05 11:05 UTC, merged

2017-09-05 11:06 UTC, Juanlu001 commented
¡Gracias @rebost!

2017-09-05 11:08 UTC, yamila-moreno commented
Fantástico! ^_^