Agregar menu para las páginas del sitio
python-spain/web pull request #118
Opened 2021-04-10 21:04 UTC by cmaureir

Actualmente el sitio tiene las páginas como palabras
dentro de la cabecera, lo que podría ser mejorado si se presenta
como un menú de navegación.

Como utilizamos bootstrap, pensé en utilizar la versión "responsive"
pero la implementación actual no transforma el menú en un botón
hamburguesa debido a que agregar jquery (y otros dos archivos JS) para
tener la funcionalidad de un botón 'responsive' me parecía demasiado.

![2021-04-10-230256_3840x1080_scrot](https://user-images.githubusercontent.com/177982/114284564-0ad9b380-9a51-11eb-8234-566964236188.png)

2021-04-11 17:10 UTC, dukebody requested changes

2021-04-11 17:10 UTC, dukebody commented on themes/pelican-alchemy/alchemy/static/css/theme.css
> +.topnav a.active {
Esto no se aplica nunca, ¿no? Ya que no le añadimos la clase `active` nunca. Al menos yo probando en local no lo veo.

2021-04-11 17:10 UTC, dukebody commented on themes/pelican-alchemy/alchemy/templates/include/header.html
> -        {% for title, link in LINKS %}
Toda la parte de links no está en el `menu.html`. Quizá deberíamos dejarla aquí entonces.

2021-04-11 17:10 UTC, dukebody commented on themes/pelican-alchemy/alchemy/templates/include/header.html
> -        {% for title, link in LINKS %}
https://github.com/python-spain/web/commit/3dcc0940de285cdcf93c538da7ff40ce815d942c

2021-04-24 15:41 UTC, dukebody commented on themes/pelican-alchemy/alchemy/templates/include/header.html
> -        {% for title, link in LINKS %}
@cmaureir te parece OK lo que puse en https://github.com/python-spain/web/commit/3dcc0940de285cdcf93c538da7ff40ce815d942c para incluirlo?

2021-04-24 17:49 UTC, cmaureir commented
Buenas @dukebody , la verdad estaba esperando a si alguien más hacia comentarios antes de aplicar los cambios jaja, pero si me parecen bien  y los puedo hacer ahora asi vamos cerrando PRs :P

2021-04-24 17:58 UTC, cmaureir commented
Lo mejora: https://github.com/python-spain/web/pull/122

2021-04-24 17:58 UTC, closed without merging